Update README.md
Netuitive/netuitive-statsd pull request #30
Opened 2018-10-19 03:44 UTC by adam-weiler

I tried to update your Readme file to point towards metricly.com instead of netuitive.com.

2018-10-19 12:26 UTC, TheConnMan requested changes
Thanks for the contribution! Just a couple suggested Metricly name changes.

2018-10-19 12:26 UTC, TheConnMan commented on README.md
> +For more information on the Netuitive StatsD Server, see our [help docs](https://www.metricly.com/support/integrations/linux/#kanchor275), or contact Netuitive support at [sales@metricly.com](mailto:
We'd still like support questions to go to support.

```suggestion
For more information on the Netuitive StatsD Server, see our [help docs](https://www.metricly.com/support/integrations/linux/#kanchor275), or contact Metricly support at [support@metricly.com](mailto:support@metricly.com).
````

2018-10-19 12:26 UTC, TheConnMan commented on README.md
> +>**Note:** This is already installed as part of the [Netuitive Linux Agent](https://www.metricly.com/support/integrations/linux/) package and does not need to be installed separately.
Just a change to Metricly.

```suggestion
>**Note:** This is already installed as part of the [Metricly Linux Agent](https://www.metricly.com/support/integrations/linux/) package and does not need to be installed separately.
```

2018-10-19 12:26 UTC, TheConnMan commented on README.md
> +The Netuitive StatsD Server interprets, aggregates, and forwards custom metrics generated from your application to [Netuitive](https://www.metricly.com). Netuitive StatsD is compatible with the follo
Another Metricly name change.

```suggestion
The Netuitive StatsD Server interprets, aggregates, and forwards custom metrics generated from your application to [Metricly](https://www.metricly.com). Netuitive StatsD is compatible with the following formats: StatsD, DogStatsD Metrics, DogStatsD Events, and DogStatsD Service Checks. Using the values instrumented from your application's key actions and data (method calls, database queries, etc.), Netuitive aggregates the values, associates them with corresponding metrics, and analyzes them in our analytics cycles.
```

2018-10-19 13:49 UTC, Grumblesmith commented
Please rebase your branch against develop

2019-03-08 02:45 UTC, rclagett commented
A new docs site has launched!

2019-03-08 02:45 UTC, closed without merging