Set minimal required version to netuitive>=0.3.4
Netuitive/netuitive-statsd pull request #31
Opened 2019-04-25 17:36 UTC by yadima

2019-04-25 17:46 UTC, rclagett approved these changes

2019-04-25 17:48 UTC, codytipton approved these changes

2019-04-25 19:21 UTC, TheConnMan requested changes

2019-04-25 19:21 UTC, TheConnMan commented on HISTORY.md
> +Version 0.4.2 - Apr 25 2019
Please add the version bump directly on the `develop` branch.

2019-04-25 21:37 UTC, Grumblesmith requested changes

2019-04-25 21:37 UTC, Grumblesmith commented on HISTORY.md
> +Version 0.4.2 - Apr 25 2019
```suggestion
Version next - MMM DD YYYY
```

2019-04-25 22:40 UTC, rclagett approved these changes

2019-04-26 10:57 UTC, TheConnMan approved these changes

2019-04-26 12:10 UTC, merged